Repository trungduong0103/snapie, pull requests merged in 2020-03, with the labels that each got.

#12 remove .idea folder
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sepm-react-native.iml
  .idea/vcs.xml
  .idea/workspace.xml
Labels: development

#14 Update README.md
  README.md
Labels: documentation

#17 Set up Express boilerplate + Write first Cloud Function
  .gitignore
  cloud-functions/functions/.gitignore
  cloud-functions/functions/index.js
  cloud-functions/functions/package-lock.json
  cloud-functions/functions/package.json
  cloud-functions/functions/vision-functions/index.js
Labels: development

#24 update .gitignore and eslint
  .gitignore
  client/.eslintrc.js
Labels: development

#36 Development: Add new function to query image using keyword to unsplash
  cloud-functions/functions/cloud-vision/index.js
  cloud-functions/functions/index.js
  cloud-functions/functions/package.json
  cloud-functions/functions/unsplash/index.js
  cloud-functions/functions/vision-functions/index.js
Labels: development

#35 set up basic testing with detox and jest
  .gitignore
  client/.gitignore
  client/e2e/config.json
  client/e2e/init.js
  client/e2e/testing/firstTest.spec.js
  client/e2e/testing/note.testing.howto.md
  client/ios/Podfile.lock
  client/package.json
  client/src/views/Home.js
  client/yarn.lock
Labels: development, enhancement
